/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chair/scene.gltf -o src/components/Chair.jsx -r public 
Author: AK STUDIO (https://sketchfab.com/inven2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-chair-af2f07d06f6349158c1d24d87f5ceb95
Title: Office chair
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

export const Chair = forwardRef(({isSelected, ...props}, ref) => {
  const { nodes, materials } = useGLTF('/models/chair/scene.gltf')
  const selectedMateriral = new THREE.MeshStandardMaterial({
    wireframe: true,
    color: "yellow",
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.531}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={isSelected ? selectedMateriral : materials.Chair} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
})

useGLTF.preload('/models/chair/scene.gltf')
